### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by Kasia1403** [Majrusz/WonderfulEnchantmentsMod#35]
[crash-2021-06-14_10.21.31-server.txt](https://github.com/Majrusz/WonderfulEnchantmentsMod/files/6646771/crash-2021-06-14_10.21.31-server.txt)

**Comment by Majrusz** [comment]
Hi, unfortunately I have stopped supporting older versions of Minecraft and have no plans to fix bugs from those versions.
