### ISSUE TITLE
Shield always have absorber and crash when broken

### ISSUE THREAD

**Issue by Ritzumi** [Majrusz/WonderfulEnchantmentsMod#5]
###### Versions
Forge: 35.1.32
Wonderful Enchantments : 0.10.0

###### Descriptions
Shield, even without absorber enchantment, will act as if it has the enchantment. And if the durability expense cost break the shield, game will crash.
###### How to reproduce
1. Create a world
2. Equip a shield
3. Get a debuff (Recommend using Spartan Weaponry since the two-handed weapon will make player always have debuff if equip something off-hand)
4. Wait until the shield run out of durability
5. Behold~
###### Log / Crash Log
Crash Log : https://gist.github.com/Ritzumi/9a79465f78b2e8dcf13c789622e7de59
Log : https://gist.github.com/Ritzumi/9423544261bfa87b74b7ba228d9c1c7c

**Comment by Majrusz** [comment]
Thanks for the feedback! In version 0.10.1 this will be fixed.
