### ISSUE TITLE
Dupe Bug

### ISSUE THREAD

**Issue by AcrazyD** [Majrusz/WonderfulEnchantmentsMod#9]
Telekinesis dupes some items when broken, Tested in 1.16.4-3.0.6.1 with Expanded Storage Old Chests, had four, after breaking the four I had twelve. I removed the enchant from my tool and no longer was duping items.

**Comment by Majrusz** [comment]
What type of blocks are you destroying? Because when I have tested it, everything works fine.

**Comment by AcrazyD** [comment]
Expanded Storage Old Chests, the diamond one is the one i noticed it with

**Comment by Majrusz** [comment]
Do you have any other mods? Because both the diamond chest and the old diamond chest work fine.

**Comment by Majrusz** [comment]
I finally found out what was causing this bug. This will be fixed in the next update.
